Fix ResNet50 official model break on post-1.15 1.x
Custom-built TF nightly packages 2019-09-22 was broken running the official ResNet50 model, caused by this CL: https://github.com/tensorflow/tensorflow/commit/304a43d655ce15c625aaabcfb7a1087e221a90e7.

```
2019-09-26 09:29:45.495883: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at dataset_ops.cc:82 : Failed precondition: RandomUniform is stateful.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: 2 root error(s) found.
  (0) Failed precondition: RandomUniform is stateful.
	 [[{{node DatasetToGraph}}]]
	 [[MultiDeviceIteratorInit/_5887]]
  (1) Failed precondition: RandomUniform is stateful.
	 [[{{node DatasetToGraph}}]]
0 successful operations.
7 derived errors ignored.
```

This PR fixes this break.